In [24]:
import numpy as np

A = np.random.randint(10, size=[3,3])
I = np.identity(3)
A

array([[0, 8, 6],
       [8, 7, 4],
       [5, 5, 1]])

In [25]:
# determinent of A
np.linalg.det(A)

126.0

In [26]:
# matrix multiplication
np.dot(A,A)

array([[ 94,  86,  38],
       [ 76, 133,  80],
       [ 45,  80,  51]])

In [28]:
A

array([[0, 8, 6],
       [8, 7, 4],
       [5, 5, 1]])

In [27]:
np.dot(A,I)

array([[0., 8., 6.],
       [8., 7., 4.],
       [5., 5., 1.]])

In [29]:
# inverse matrix of A
np.linalg.inv(A)

array([[-0.1031746 ,  0.17460317, -0.07936508],
       [ 0.0952381 , -0.23809524,  0.38095238],
       [ 0.03968254,  0.31746032, -0.50793651]])

In [30]:
# eigen values and eigen vectors of A
np.linalg.eig(A)

(array([15.45225522, -6.11984384, -1.33241138]),
 array([[ 0.54145666,  0.85278471,  0.25595007],
        [ 0.71882829, -0.42933286, -0.60693542],
        [ 0.43601671, -0.29737439,  0.75240877]]))

In [20]:
a = 0
for i in range(6):
    a+=2
    print(i,":",a)

0 : 2
1 : 4
2 : 6
3 : 8
4 : 10
5 : 12
